# Generated by Django 5.0.6 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_currence_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='currence',
            new_name='currency',
        ),
    ]
