# Generated by Django 5.0.6 on 2024-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
