# Generated by Django 5.0.6 on 2024-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_actor_profile_pic_director_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
